# Generated by Django 4.2.4 on 2024-06-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='Адрес электронной почты')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент рассылки',
                'verbose_name_plural': 'Клиенты рассылки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема сообщения')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(blank=True, null=True, verbose_name='Время начала рассылки')),
                ('end_time', models.DateField(blank=True, null=True, verbose_name='Время окончания рассылки')),
                ('frequency', models.CharField(choices=[('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='daily', max_length=50, verbose_name='Период рассылки')),
                ('status', models.CharField(choices=[('created', 'created'), ('started', 'started'), ('completed', 'completed')], default='created', max_length=50, verbose_name='Статус рассылки')),
                ('datetime', models.DateField(auto_now_add=True, null=True, verbose_name='дата и время попытки')),
                ('attempt', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='ответ сервера')),
                ('distribution_client', models.ManyToManyField(to='distribution.distributionclient', verbose_name='Клиент рассылки')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.message', verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
